[workspace]
members = [
    "src",
    "crates/core",
    "crates/executor",
    "crates/orchestrator",
    "crates/plugins",
    "plugins",
    "cmd",
    "wasm"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
